name: Build and Deploy VidStreamX (.NET + Angular)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: VidStreamX
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore .NET packages
    - name: Restore .NET dependencies
      run: dotnet restore ./VidStreamX

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Install Angular dependencies
    - name: Install Angular dependencies
      working-directory: ./vidstreamx-UI
      run: npm install

    # Build Angular
    - name: Build Angular App
      working-directory: ./vidstreamx-UI
      run: npm run build -- --configuration production

    # Copy Angular build into .NET wwwroot
    - name: Copy Angular build to .NET API
      run: |
        echo "Ensuring wwwroot exists..."
        mkdir -p ./VidStreamX/wwwroot

        echo "Cleaning existing wwwroot..."
        rm -rf ./VidStreamX/wwwroot/*

        echo "Copying Angular dist files..."
        cp -r ./vidstreamx-UI/dist/vidstreamx-ui/* ./VidStreamX/wwwroot/

        echo "Frontend copied successfully."

    # Publish .NET App
    - name: Publish .NET API
      run: dotnet publish ./VidStreamX -c Release -o './publish'

    # Upload artifact
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
